services:
  db:
    image: postgres:15-alpine
    command: -c 'max_connections=1000' -c 'shared_buffers=1GB'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asdgekvnknrgkwuer
      POSTGRES_DB: ghibli
      MAX_CONNECTIONS: 100
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    hostname: postgres
    networks:
      - app-network

  app:
    build: .
    env_file:
      - .env
    depends_on:
      - db
      - minio
    ports:
      - 8080:8080
    networks:
      - app-network

  minio:
    image: minio/minio
    container_name: minio
    environment:
            MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
            MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
            MINIO_SERVER_URL: https://minio.stylish-images.ru
            MINIO_BROWSER_REDIRECT_URL: https://minio.stylish-images.ru
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}" --address ":9000"
    ports:
            - "${MINIO_PORT}:9000" # API
            - "${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}" # Console
    volumes:
            - minio_data:/data
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test:
          [
              "CMD",
              "curl",
              "-f",
              "http://localhost:9000/minio/health/live",
          ]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  app-network:
    driver: bridge

volumes:
  app_data:
  postgres_data:
  minio_data:
